# Generated by Django 4.1 on 2022-09-06 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='in_acrive',
            new_name='in_active',
        ),
    ]
